### ISSUE TITLE
Error with Geometry Shader - "Sequence contains more than one element"

### ISSUE THREAD

**Issue by lunanane** [vvvv/VL.Stride#530]
Hey :)

I am working on the GPU implementation of Lines and ported the classic ConnectAll patch from InstanceNoodles.

The shader produces a bug and throws an error.

When double clicking the DrawLinesShader in the ConnectAll Subpatch, it throws an exception saying "Sequence contains more than one element".

I am pretty confident that the shader is working. It also makes correct use of streams object as far as I researched.

So I wonder if the geometry shader part makes other kind of problems in the render pipeline.

I attached the patch.

[ConnectAll_Gamma.zip](https://github.com/vvvv/VL.Stride/files/7675833/ConnectAll_Gamma.zip)

Would be great if you could have a look at it.

Thanks and wishing a good week,
Luna.

**Comment by tebjan** [comment]
@lunanane is the attached zip still the latest state of the code?

**Comment by tebjan** [comment]
the shader and the patch runs on open and shows this output, tested on a laptop with nvidia GPU:
![image](https://user-images.githubusercontent.com/1094716/146571237-1e364666-3882-4a80-ae36-aebcf47c7e98.png)


so the issue you are talking about is the double click on the shader? that seems to be an issue with the node browser, not the shader...
```
System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.ImmutableArrayExtensions.SingleOrDefault[T](ImmutableArray`1 immutableArray, Func`2 predicate)
   at VL.HDE.SymbolBrowsers.NodeBrowser.<GetNecessaryUpcomingDecisions>d__72.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at VL.HDE.SymbolBrowsers.SymbolBrowser.ReloadSymbols()
   at VL.HDE.SymbolBrowsers.SymbolBrowser.TextEdit_TextChanged(String text, TextEditor sender)
   at VL.HDE.SymbolBrowsers.SymbolBrowser.Show(Boolean modal, IVLFactory factory, EventHandler canceled)
   at VL.HDE.SymbolBrowsers.NodeBrowser.Show(Boolean modal, IVLFactory factory, EventHandler`1 padCreated, EventHandler`1 applicationCreated, EventHandler canceled)
   at VL.Lang.View.CanvasView.OpenNodeBrowser(Form owner, VMouseEventArgs doubleClick, Point screenPoint, Boolean createIOBox)
   at VL.Lang.View.CanvasView.CanvasDecisionMouseHandler.DoubleClickMethod(VMouseEventArgs firstClick, VMouseEventArgs click)
   at VL.Core.Viewer.Handler.<>c__DisplayClass18_0.<OnDoubleClick>b__0(VMouseEventArgs down)
   at VL.Core.Viewer.Handler.ParallelMouseHandler.MouseDown(VMouseEventArgs arg)
   at VL.Lang.View.CanvasView.CanvasDecisionMouseHandler.MouseDown(VMouseEventArgs arg)
   at VL.Lang.View.CanvasView.HandleMouseDown(Object sender, VMouseEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
vvvv
    Assembly Version: 2021.4.0.0
    Win32 Version: 2021.4.2.691
    CodeBase: file:///C:/Program%20Files/vvvv/vvvv_gamma_2021.4.2/vvvv.exe
----------------------------------------

```
